// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package api

import (
	"database/sql"
)

type Image struct {
	ID      int64
	Name    string
	Data    string
	Created interface{}
	Deleted sql.NullBool
}
