// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package api

import (
	"database/sql"
)

type Image struct {
	ID      int64
	Data    string
	Created string
	Deleted sql.NullInt32
}
