version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    restart: always
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    restart: always
    # volumes:
    #   - ./webapp:/opt/webapp
