// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Note struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	UserID    int64        `json:"userId"`
	CreatedAt sql.NullTime `json:"createdAt"`
}

type Session struct {
	ID           string       `json:"id"`
	UserID       int64        `json:"userId"`
	RefreshToken string       `json:"refreshToken"`
	IsRevoked    bool         `json:"isRevoked"`
	ExpiresAt    time.Time    `json:"expiresAt"`
	CreatedAt    sql.NullTime `json:"createdAt"`
}

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"createdAt"`
}
