// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type Image struct {
	ID      int64         `json:"id"`
	Data    string        `json:"data"`
	Created string        `json:"created"`
	Deleted sql.NullInt32 `json:"deleted"`
}
