// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateImage(ctx context.Context, data string) (Image, error)
	DeleteImage(ctx context.Context, id int64) error
	GetImage(ctx context.Context, id int64) (Image, error)
	ListImages(ctx context.Context) ([]Image, error)
	SoftDeleteImage(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
