// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/meads/firstly-api/security (interfaces: Hasher)
//
// Generated by this command:
//
//	mockgen -package security -destination ./security/hmac_mock.go github.com/meads/firstly-api/security Hasher
//

// Package security is a generated GoMock package.
package security

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHasher is a mock of Hasher interface.
type MockHasher struct {
	ctrl     *gomock.Controller
	recorder *MockHasherMockRecorder
	isgomock struct{}
}

// MockHasherMockRecorder is the mock recorder for MockHasher.
type MockHasherMockRecorder struct {
	mock *MockHasher
}

// NewMockHasher creates a new mock instance.
func NewMockHasher(ctrl *gomock.Controller) *MockHasher {
	mock := &MockHasher{ctrl: ctrl}
	mock.recorder = &MockHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasher) EXPECT() *MockHasherMockRecorder {
	return m.recorder
}

// GeneratePasswordHash mocks base method.
func (m *MockHasher) GeneratePasswordHash(phrase []byte, salt string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePasswordHash", phrase, salt)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePasswordHash indicates an expected call of GeneratePasswordHash.
func (mr *MockHasherMockRecorder) GeneratePasswordHash(phrase, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePasswordHash", reflect.TypeOf((*MockHasher)(nil).GeneratePasswordHash), phrase, salt)
}

// GenerateSalt mocks base method.
func (m *MockHasher) GenerateSalt() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSalt")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSalt indicates an expected call of GenerateSalt.
func (mr *MockHasherMockRecorder) GenerateSalt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSalt", reflect.TypeOf((*MockHasher)(nil).GenerateSalt))
}

// IsValidPassword mocks base method.
func (m *MockHasher) IsValidPassword(phrase []byte, salt, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidPassword", phrase, salt, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidPassword indicates an expected call of IsValidPassword.
func (mr *MockHasherMockRecorder) IsValidPassword(phrase, salt, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidPassword", reflect.TypeOf((*MockHasher)(nil).IsValidPassword), phrase, salt, password)
}
