// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: account.sql

package db

import (
	"context"
)

const accountExists = `-- name: AccountExists :one
SELECT EXISTS(SELECT 1 FROM account WHERE id = $1)
`

func (q *Queries) AccountExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
  username, phrase, salt, created
) VALUES (
  $1, $2, $3, NOW()
)
RETURNING id, username, phrase, salt, created, updated, deleted
`

type CreateAccountParams struct {
	Username string `json:"username"`
	Phrase   []byte `json:"phrase"`
	Salt     string `json:"salt"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Username, arg.Phrase, arg.Salt)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phrase,
		&i.Salt,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, phrase, salt, created, updated, deleted FROM account
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phrase,
		&i.Salt,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, phrase, salt, created, updated, deleted FROM account
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phrase,
		&i.Salt,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, created, deleted FROM account LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAccountsRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Created  string `json:"created"`
	Deleted  bool   `json:"deleted"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Created,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE account
SET deleted = 1
WHERE id = $1
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteAccount, id)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE account
SET phrase = $1, updated = NOW()
WHERE id = $2
RETURNING updated
`

type UpdateAccountParams struct {
	Phrase []byte `json:"phrase"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount, arg.Phrase, arg.ID)
	return err
}
