// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: image.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO image (
  data, created
) VALUES (
  $1, NOW()
)
RETURNING id, data, memo, created, updated, deleted
`

func (q *Queries) CreateImage(ctx context.Context, data string) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, data)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.Memo,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM image
WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, data, memo, created, updated, deleted FROM image
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImage(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.Memo,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, data, memo, created, updated, deleted FROM image LIMIT $1 OFFSET $2
`

type ListImagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Memo,
			&i.Created,
			&i.Updated,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteImage = `-- name: SoftDeleteImage :exec
UPDATE image
SET deleted = 1
WHERE id = $1
`

func (q *Queries) SoftDeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteImage, id)
	return err
}

const updateImage = `-- name: UpdateImage :exec
UPDATE image
SET memo = $1, updated = NOW()
WHERE id = $2
RETURNING updated
`

type UpdateImageParams struct {
	Memo string `json:"memo"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) error {
	_, err := q.db.ExecContext(ctx, updateImage, arg.Memo, arg.ID)
	return err
}
