// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Account struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Phrase   []byte `json:"phrase"`
	Salt     string `json:"salt"`
	Created  string `json:"created"`
	Updated  string `json:"updated"`
	Deleted  bool   `json:"deleted"`
}
