// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import ()

type Image struct {
	ID      int64  `json:"id"`
	Data    string `json:"data"`
	Memo    string `json:"memo"`
	Created string `json:"created"`
	Updated string `json:"updated"`
	Deleted bool   `json:"deleted"`
}
