// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id int64) error
	GetSession(ctx context.Context, id string) (Session, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeSession(ctx context.Context, id string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UserExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
