// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, data string) (Image, error)
	Delete(ctx context.Context, id int64) error
	Get(ctx context.Context, id int64) (Image, error)
	List(ctx context.Context, arg ListParams) ([]Image, error)
	SoftDelete(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
